# Generated by Django 4.1 on 2022-08-10 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('registration', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('position_code', models.IntegerField(choices=[(10, 'Cientista de Dados'), (20, 'Especialista em Business Intelligence'), (30, 'Desenvolvedor Mobile Sênior'), (31, 'Desenvolvedor Mobile Pleno'), (32, 'Desenvolvedor Junior'), (50, 'Gerente de Projetos')], verbose_name='Cargo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('date_admission', models.DateField(verbose_name='Data de admissão')),
                ('commission', models.BooleanField(verbose_name='Comissão')),
                ('active_registration', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=True, verbose_name='Código')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('base_salary', models.FloatField(verbose_name='Salário')),
                ('commission', models.FloatField(verbose_name='Comissão')),
            ],
        ),
        migrations.CreateModel(
            name='PayStubs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data de emissão')),
                ('absences', models.IntegerField(default=0, verbose_name='Faltas')),
                ('absentee_discount', models.FloatField(null=True, verbose_name='Desconto de faltas')),
                ('fgts_base', models.FloatField(null=True, verbose_name='Base de Cáculo FGTS')),
                ('fgts', models.FloatField(null=True, verbose_name='FGTS')),
                ('inss_base', models.FloatField(null=True, verbose_name='Base de Cáculo INSS')),
                ('inss_discount', models.FloatField(null=True, verbose_name='Desconto INSS')),
                ('inss_aliquot', models.FloatField(null=True, verbose_name='Alíquota INSS')),
                ('irrf_base', models.FloatField(null=True, verbose_name='Base de Cáculo IRRF')),
                ('irrf_discount', models.FloatField(null=True, verbose_name='Desconto IRRF')),
                ('irrf_aliquot', models.FloatField(null=True, verbose_name='Alíquota IRRF')),
                ('total_discount', models.FloatField(null=True, verbose_name='Desconto total')),
                ('total_salaries', models.FloatField(null=True, verbose_name='Vencimentos totais')),
                ('salary_recievable', models.FloatField(null=True, verbose_name='Líquido a receber')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_funcionário', to='pay_stubs.employee', verbose_name='ID Funcionário')),
            ],
        ),
    ]
